group: bluezone
dist: precise
language: node_js
node_js:
  - "6.11"
# npm dependency 'heapdump' needs a C++11 supporting compiler
# so install g++4.8 and set env var CXX to use it.
env:
  global:
  - CXX=g++-4.8
sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.8 -y
  - npm install -g npm@^3
