$integration: http://ibm.com/appconnect/integration/v2/integrationFile
integration:
  type: api
  trigger-interfaces:
    trigger-interface-1:
      triggers:
        retrieveDatabricks:
          assembly:
            $ref: '#/integration/assemblies/assembly-1'
          input-context:
            data: retrieveDatabricks
          output-context:
            data: retrieveDatabricks
      options:
        resources:
          - business-object: Databricks
            triggers:
              retrieve: retrieveDatabricks
            model:
              $ref: '#/models/Databricks'
      type: api-trigger
  action-interfaces:
    action-interface-1:
      type: api-action
      business-object: TABLE appconn
      connector-type: databricks
      actions:
        getAllRows: {}
      options:
        connectorServiceOptions:
          httpMethod: get
          path: resources/TABLE%20appconn/operations/getAllRows
          action: retrievewithwhere
  assemblies:
    assembly-1:
      assembly:
        execute:
          - custom-action:
              name: Databricks Retrieve appconn record
              target:
                $ref: '#/integration/action-interfaces/action-interface-1'
              allow-empty-output: false
              filter:
                limit: 10
                where:
                  id: '{{$api.id}}'
                input:
                  - variable: flowDetails
                    $ref: '#/flowDetails'
                  - variable: api
                    $ref: '#/trigger/api/parameters'
              allow-truncation: false
              pagination-type: SKIP_LIMIT
              action: getAllRows
              map:
                $map: http://ibm.com/appconnect/map/v1
                mappings: []
                input: []
          - response:
              name: response
              reply-maps:
                - title: Databricks successfully retrieved
                  status-code: '200'
                  map:
                    mappings:
                      - id:
                          template: '{{$api.id}}'
                      - response:
                          expression: '$DatabricksRetrieveappconnrecord '
                    $map: http://ibm.com/appconnect/map/v1
                    input:
                      - variable: DatabricksRetrieveappconnrecord
                        $ref: >-
                          #/node-output/Databricks Retrieve appconn
                          record/response/payload
                      - variable: flowDetails
                        $ref: '#/flowDetails'
                      - variable: api
                        $ref: '#/trigger/api/parameters'
                  input:
                    - variable: DatabricksRetrieveappconnrecord
                      $ref: >-
                        #/node-output/Databricks Retrieve appconn
                        record/response/payload
                    - variable: flowDetails
                      $ref: '#/flowDetails'
                    - variable: api
                      $ref: '#/trigger/api/parameters'
  name: Retrieve by id from appconn table
models:
  Databricks:
    name: Databricks
    plural: Databricks
    properties:
      id:
        required: false
        id: true
        type: string
      response:
        required: false
        id: false
        type:
          - type: {}
    operations:
      retrieve: '#/integration/assemblies/assembly-1'
    description: 'API to expose Databricks data via REST APIs to other applications'
